update to rust 1.81 and fix bug in --clean option of the build command
following error could occur on windows:
Error: Das System kann die angegebene Datei nicht finden. (os error 2)
error: process didn't exit successfully: `target\debug\neptungen.exe build --clean` (exit code: 1)

this happens if the output folder for the generated page did not exist.